### PR TITLE
pandas dataframe render

### PR DESCRIPTION
**Pull request by MichaMucha**
I was playing with the examples you shared and built this basic pd.DataFrame render

Thanks for your great work! I love ipyvuetify

### CODE REVIEW

**Comment by mariobuikhuizen** [comment]
Thanks! This is an excellent solution to QuantStack/voila-vuetify#12. 

Thanks for contributing this example/reusable widget.

It might be an idea to include widgets like this in a contrib package.

**Comment by MichaMucha** [comment]
Awesome, I didn't notice that issue before, glad it's useful!
Please feel free to share suggestions abut the direction for potential contributions, I'd be glad to do something.

**Comment by MatthieuMayer** [comment]
Hi all, 

First of all thank you for the great work on ipyvuetify, which is a very promising tool !!
I happened to find the related closed issue on DataFrames render mentioning that: 

> Because of the missing v-slot features it's not usable right now.

I would like to ask if, since last august, the v-slot has known any progress toward making v.DataTable completely functional without the template usage? Thanks for your answer.

**Comment by mariobuikhuizen** [comment]
Thanks for your question. Yes, v-slot has been implemented since! You can find how to use it in the docs: https://github.com/mariobuikhuizen/ipyvuetify#scoped-slots and examples: https://github.com/mariobuikhuizen/ipyvuetify/blob/master/examples/Examples.ipynb

snippet of v-slot use:
```python
v.Tooltip(bottom=True, v_slots=[{
        'name': 'activator',
        'variable': 'tooltip',
        'children': v.Btn(v_on='tooltip.on', color='primary', class_='ma-2', children=[
           'tooltip' 
        ]),
    }], children=[
        'Insert tooltip text here'
    ])  
```

**Comment by MatthieuMayer** [comment]
Hi Mario, 
Thx for your quick reply, I believe though I was not specific enough, my bad. 
My question was specifically referring to the [Display pandas dataframe as a table #12](https://github.com/voila-dashboards/voila-vuetify/issues/12#) closed issue.

In this discussion, a user is trying use the v.DataTable() ipyvuetify widget but cannot make it work (as I cannot either so far) and I believe you answer about this issue is the following :

>(1b) The ipyvuetify DataTable widget is the python wrapper around vuetify's v-data-table. Because of the missing v-slot features it's not usable right now. This widget is still included because all wrappers are auto generated. The VuetifyTemplate was used as a workaround.

So my not-specific-enough question (sorry again) about the v-slot feature actually meant to ask if the v.DataTable ipyvuetify widget is now fully functional.

So far I can make it work with the template with this small example: 
```
class MyTable(v.VuetifyTemplate):
    headers = List([]).tag(sync=True)
    items = List([]).tag(sync=True)
    template = Unicode('''
        <v-data-table
            :headers=headers
            :items=items
            hide-default-footer
            class="elevation-1"
        ></v-data-table>
    ''').tag(sync=True)
    
    def __init__(self, *args):
        super().__init__(*args)
        self.headers = [{'text': 'Dessert (100g serving)','value': 'name'},
                        {'text': 'Calories', 'value': 'calories'},
                        {'text': 'Fat (g)', 'value': 'fat'},
                        {'text': 'Protein (g)', 'value': 'protein'}
                       ]
        
        self.items = [{'name': 'Frozen Yogurt', 'calories': '159', 'fat': '6.0', 'protein': '4.0'},
                      {'name': 'Ice cream sandwich', 'calories': '237', 'fat': '9.0', 'protein': '4.3'},
                      {'name': 'Eclair', 'calories': '262', 'fat': '16.0', 'protein': '6.0'},
                      {'name': 'Cupcake', 'calories': '305', 'fat': '3.7', 'protein': '4.3'}
                     ]

MyTable()
```

But I cannot make it work when I try to translate it to the pythonic usage with following code:
```
headers = [{'text': 'Dessert (100g serving)','value': 'name'},
           {'text': 'Calories', 'value': 'calories'},
           {'text': 'Fat (g)', 'value': 'fat'},
           {'text': 'Protein (g)', 'value': 'protein'}
          ]

items = [{'name': 'Frozen Yogurt', 'calories': '159', 'fat': '6.0', 'protein': '4.0'},
         {'name': 'Ice cream sandwich', 'calories': '237', 'fat': '9.0', 'protein': '4.3'},
         {'name': 'Eclair', 'calories': '262', 'fat': '16.0', 'protein': '6.0'},
         {'name': 'Cupcake', 'calories': '305', 'fat': '3.7', 'protein': '4.3'}
        ]

v.DataTable(headers=[{'text': 'Dessert (100g serving)','value': 'name'}], 
            items=[{'name': 'Frozen Yogurt', 'calories': '159', 'fat': '6.0', 'protein': '4.0'}], 
            hide_default_footer=True) 
```

Am I doing something wrong here or is the v.DataTable still not fully functional ? And if so, is it planned on evolving anytime soon ? 

Note: I am happy to be able to use the template as a replacement solution so far, using the pythonic form, though, would make my project consistent with using other ipyvuetify widgets in their pythonic form.

**Comment by mariobuikhuizen** [comment]
I see that since Vuetify 2.0 v-data-table can be used without slots. But now there is another problem: the `headers` property is missing from the generated ipyvuetify code.

Thanks for reporting this bug!

**Pull request merged**
